CREATE TABLE orders (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_number            VARCHAR(20)   NULL UNIQUE,
    offer_id                BIGINT        NOT NULL UNIQUE,
    customer_id             BIGINT        NOT NULL,
    created_by_id           BIGINT        NOT NULL,
    origin_airport          VARCHAR(3)    NOT NULL,
    destination_airport     VARCHAR(3)    NOT NULL,
    service_type            VARCHAR(30)   NOT NULL,
    commodity                VARCHAR(150) NOT NULL,
    chargeable_weight_kg    DECIMAL(10,2) NOT NULL,
    requested_capacity_kg   DECIMAL(10,2) NOT NULL,
    currency                VARCHAR(3)    NOT NULL,
    total_price             DECIMAL(10,2) NOT NULL,
    requested_ship_date     DATE          NOT NULL,
    special_instructions    VARCHAR(500)  NULL,

    consignor_name             VARCHAR(150) NOT NULL,
    consignor_company          VARCHAR(150) NOT NULL,
    consignor_address_line1    VARCHAR(200) NOT NULL,
    consignor_address_line2    VARCHAR(200) NULL,
    consignor_city             VARCHAR(100) NOT NULL,
    consignor_state_province   VARCHAR(100) NULL,
    consignor_postal_code      VARCHAR(20)  NULL,
    consignor_country          VARCHAR(100) NOT NULL,
    consignor_phone            VARCHAR(30)  NOT NULL,
    consignor_email            VARCHAR(150) NULL,

    consignee_name             VARCHAR(150) NOT NULL,
    consignee_company          VARCHAR(150) NOT NULL,
    consignee_address_line1    VARCHAR(200) NOT NULL,
    consignee_address_line2    VARCHAR(200) NULL,
    consignee_city             VARCHAR(100) NOT NULL,
    consignee_state_province   VARCHAR(100) NULL,
    consignee_postal_code      VARCHAR(20)  NULL,
    consignee_country          VARCHAR(100) NOT NULL,
    consignee_phone            VARCHAR(30)  NOT NULL,
    consignee_email            VARCHAR(150) NULL,

    notify_party_name             VARCHAR(150) NULL,
    notify_party_company          VARCHAR(150) NULL,
    notify_party_address_line1    VARCHAR(200) NULL,
    notify_party_address_line2    VARCHAR(200) NULL,
    notify_party_city             VARCHAR(100) NULL,
    notify_party_state_province   VARCHAR(100) NULL,
    notify_party_postal_code      VARCHAR(20)  NULL,
    notify_party_country          VARCHAR(100) NULL,
    notify_party_phone            VARCHAR(30)  NULL,
    notify_party_email            VARCHAR(150) NULL,

    status                  VARCHAR(20)   NOT NULL DEFAULT 'CREATED',
    created_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (offer_id)       REFERENCES offers(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_id)    REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id)  REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_order_status (status),
    INDEX idx_order_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE order_ancillary_services (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id     BIGINT        NOT NULL,
    service_type VARCHAR(30)   NOT NULL,
    price        DECIMAL(10,2) NOT NULL,
    notes        VARCHAR(200)  NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    INDEX idx_order_ancillary_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
