CREATE TABLE offers (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    offer_number            VARCHAR(20)   NULL UNIQUE,
    customer_id             BIGINT        NOT NULL,
    created_by_id           BIGINT        NOT NULL,
    origin_airport          VARCHAR(3)    NOT NULL,
    destination_airport     VARCHAR(3)    NOT NULL,
    service_type            VARCHAR(30)   NOT NULL,
    commodity                VARCHAR(150) NOT NULL,
    weight_kg               DECIMAL(10,2) NOT NULL,
    length_cm               DECIMAL(10,2) NULL,
    width_cm                DECIMAL(10,2) NULL,
    height_cm               DECIMAL(10,2) NULL,
    volumetric_weight_kg    DECIMAL(10,2) NULL,
    chargeable_weight_kg    DECIMAL(10,2) NOT NULL,
    temperature_requirement VARCHAR(30)   NOT NULL DEFAULT 'NONE',
    dangerous_goods         BOOLEAN       NOT NULL DEFAULT FALSE,
    dg_class                VARCHAR(100)  NULL,
    transit_preference      VARCHAR(20)   NOT NULL DEFAULT 'STANDARD',
    estimated_transit_hours INT           NOT NULL,
    requested_capacity_kg   DECIMAL(10,2) NOT NULL,
    capacity_available      BOOLEAN       NOT NULL DEFAULT TRUE,
    rate_card_id            BIGINT        NULL,
    rate_type               VARCHAR(20)   NOT NULL,
    currency                VARCHAR(3)    NOT NULL,
    base_charge             DECIMAL(10,2) NOT NULL,
    fuel_surcharge          DECIMAL(10,2) NOT NULL DEFAULT 0,
    security_surcharge      DECIMAL(10,2) NOT NULL DEFAULT 0,
    screening_fee           DECIMAL(10,2) NOT NULL DEFAULT 0,
    terminal_handling_fee   DECIMAL(10,2) NOT NULL DEFAULT 0,
    customs_fee             DECIMAL(10,2) NOT NULL DEFAULT 0,
    ancillary_total         DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_price             DECIMAL(10,2) NOT NULL,
    declared_value          DECIMAL(10,2) NULL,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    valid_from              DATETIME      NOT NULL,
    valid_until             DATETIME      NOT NULL,
    capacity_hold_until     DATETIME      NOT NULL,
    version                 INT           NOT NULL DEFAULT 1,
    parent_offer_id         BIGINT        NULL,
    created_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id)     REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_id)   REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (rate_card_id)    REFERENCES rate_cards(id) ON DELETE SET NULL,
    FOREIGN KEY (parent_offer_id) REFERENCES offers(id) ON DELETE SET NULL,
    INDEX idx_offer_status (status),
    INDEX idx_offer_customer (customer_id),
    INDEX idx_offer_route (origin_airport, destination_airport)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE offer_ancillary_services (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    offer_id     BIGINT        NOT NULL,
    service_type VARCHAR(30)   NOT NULL,
    price        DECIMAL(10,2) NOT NULL,
    notes        VARCHAR(200)  NULL,
    FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE,
    INDEX idx_ancillary_offer (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
